
name: CI/CD Pipeline DevOps

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # JOB 1 : Tests de l'application
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout du code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Installation des dépendances
      run: npm ci
      
    - name: Execution des tests
      run: npm test
      
    - name: Audit de sécurité npm
      run: npm audit --audit-level moderate

  # JOB 2 : Build Docker (s'exécute seulement si les tests passent)
  build-docker:
    runs-on: ubuntu-latest
    needs: test  # Dépend du job test
    
    steps:
    - name: Checkout du code
      uses: actions/checkout@v4
      
    - name: Build de l'image Docker
      run: |
        docker build -t mon-app-cobaye .
        echo "✅ Image Docker construite avec succès"
        
    - name: Liste des images Docker
      run: docker images
