name: CI/CD Pipeline Optimisé

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10  # Timeout après 10 minutes max
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'  # ✅ Active le cache npm
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run tests
      run: npm test
      
    - name: Security audit
      run: npm audit --audit-level moderate
      timeout-minutes: 2  # Timeout spécifique pour npm audit

  build-docker:
    runs-on: ubuntu-latest
    needs: test
    timeout-minutes: 8
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Build Docker image
      run: |
        docker build -t mon-app-cobaye .
        echo "✅ Docker image built successfully"
        
    - name: List Docker images
      run: docker images